[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = false

### See more config options https://github.com/foundry-rs/foundry/tree/master/config
[rpc_endpoints]
11155420 = "https://sepolia.optimism.io"

[etherscan]
11155420 = { key = "RCBPWE6ZQJZFX1CVKG52AN6R7SG468D6EE", url = "https://sepolia-optimism.etherscan.io/api"}
